### PR TITLE
Read CI config file for log path and extension change before using default path and extension

### PR DESCRIPTION
**Pull request by sagarkaurav**
Read CI config file for log path and extension change before using default path and extension.
This will adjust log file loading according to project config setting

### CODE REVIEW

**Comment by rvaishnav01** [comment]
what is include file location CILogViewer.php file and logs.php file

**Comment by SeunMatt** [comment]
Hello, @rvaishnav01 are you asking of where to place the files CILogViewer.php and logs.php?
If yes, they should be in the vendors folder of your project if you install it via composer.

Please see the readme docs for how to integrate it into your project and use the class in your controller.

If this does not address your question, please rephrase.
Cheers

**Comment by sagarkaurav** [comment]
Hi.. @SeunMatt can we merge this feature to master branch  or there is any improvement needs to make.

**Comment by SeunMatt** [comment]
Hello @sagarkaurav 

This is in progress and if there's any need for improvements. I will get back to you. 
Thanks

**Comment by sagarkaurav** [comment]
@SeunMatt :+1:

**Pull request merged**
